### ISSUE TITLE
[Tracker] OG Bosca Ceoil issue reports

### ISSUE THREAD

**Issue by YuriSizov** [YuriSizov/boscaceoil-blue#49]
Since the [original repository is archived](https://github.com/TerryCavanagh/boscaceoil), we can't reply to the open issues there (per GitHub's policies, even maintainers/collaborators cannot do that). So here's a tracker for issues still open there with an update on their status in Bosca Ceoil Blue.

## Rewrite/port proposals

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/47
- [x] https://github.com/TerryCavanagh/boscaceoil/issues/87
- [x] https://github.com/TerryCavanagh/boscaceoil/issues/96

Status: ✅ **Resolved**, **3.0**.

Well, hello there! These proposals are generally made obsolete by the existence of this project. Both Bosca Ceoil and its synthesizer, SiON, have been ported to a new tech stack and are supported on all desktop platforms with web and mobile versions coming in the future.

## Bug reports

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/37
  - Status: ✅ **Resolved**, **3.0-3.1**.
  - Bosca Ceoil Blue has a system that tracks all changes and makes sure none of your actions result in progress loss, prompting you with a confirmation dialog. 
  - As of version 3.1, the <kbd>Esc</kbd> key always triggers the confirmation dialog when you press it to quit the app, even if there are no unsaved changes. The key is also unbound in the web version, as it doesn't make sense there

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/40
  - Status: ✅ **Resolved**, **3.1**.
  - As of version 3.1, notes are completely cut off when pausing or stopping, and the effector is reset to avoid sounds from effects leaking.
  - Tracked here: https://github.com/YuriSizov/boscaceoil-blue/issues/56.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/55
  - Status: ✅ **Resolved**, **3.0**.
  - Since the new version is a complete rewrite using a different stack, such issues are unlikely. So considering resolved, unless there is a new report (but even then, it'd be a completely new issue).

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/57
  - Status: ✅ **Resolved**, **3.0**.
  - Shouldn't be a problem in the new version.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/66
  - Status: ✅ **Resolved**, **3.0**.
  - This is fixed in Bosca Ceoil Blue. The issue was that the name of the instrument was treated as unique in some places, even though it wasn't. I checked, and there are two collisions in the original Bosca: "Marimba" and "Trumpet". Those were never accessible in the OG, which means that the new version has two extra instruments without breaking compat! Cool.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/68
  - Status: ✅ **Resolved**, **3.0**.
  - I can confirm the crash in the original Bosca. There is a line that tries to register the app to open .ceol files, but it doesn't seem to do anything, and if you manually set up file association, that line causes an error-less crash. There is no such issue in the new version (but it also doesn't try to create such file association).

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/83
  - Status: ✅ **Resolved**, **3.0**.
  - I can confirm the issue in the original Bosca, and it seems to be resolved in Bosca Ceoil Blue from my testing.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/85
  - Status: ✅ **Resolved**, **3.0**.
  - Shouldn't be a problem with the new version.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/93
  - Status: ✅ **Resolved**, **3.0**.
  - Shouldn't be a problem with the new version.

### Exporters and importers

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/36
  - Status: ✅ **Resolved**, **3.0**.
  - The provided .ceol file seems to crash in the original app due to some indexing problem. It doesn't crash in Bosca Ceoil Blue and produces an export.
  - However, **!!! DO NOT PLAY THIS FILE IN BOSCA !!!**, especially with headphones on! It's just a lot of screeching sounds, and is extremely unpleasant. Not sure if it was intended this way or not. The XM file is somewhat easier to listen to, probably because it cannot go very high with the pitch.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/38
  - Status: ✅ **Resolved**, **3.0-3.1**.
  - I agree that this is an annoying issue, which is why I have fixed it in 3.0 and improved further in 3.1. Ideally we'd want to listen to the generated output until the threshold for "silence" is reached, but I'm not sure how to do that yet. Should be possible though.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/56
  - Status: ✅ **Resolved**, **3.0**.
  - This should be fixed as well. I reimplemented all exporters anew, following the respective specs and other documentation I could find. Without an example, I will consider this resolved.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/65
  - Status: ✅ **Resolved**, **3.0**.
  - This should be fixed as well. Wav exports specifically are nothing but replaying all the same notes across all patterns and arrangement bars once from the top. And recording the results as you do. So there shouldn't be any specific bugs related to the number of bars. But all exports, Wav included, were a subject to the issues above where the export would just end at the last bar, even if there was some residual sound still playing. Which is fixed in Bosca Ceoil Blue.

### Platforms and porting

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/60
  - Status: ✅ **Resolved**, **3.1**.
  - As of version 3.1 the web version is officially supported, and has dedicated file I/O flow specific to this platform. You can load files from your local filesystem, and on saves/exports files get downloaded. This works correctly in both Chrome and Firefox.
  - Tracked here: https://github.com/YuriSizov/boscaceoil-blue/issues/8.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/89
  - Status: ✅ **Resolved**, **3.0**.
  - We can chalk that up to some quirks of the degrading Flash ecosystem. There shouldn't be such issues in the current version, on any of the platforms.

#### "Bosca doesn't work on macOS"

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/73
- [x] https://github.com/TerryCavanagh/boscaceoil/issues/84
- [x] https://github.com/TerryCavanagh/boscaceoil/issues/88
- [x] https://github.com/TerryCavanagh/boscaceoil/issues/90
- [x] https://github.com/TerryCavanagh/boscaceoil/issues/98
- [x] https://github.com/TerryCavanagh/boscaceoil/issues/107

Status: ✅ **Resolved**, **3.0**.

Bosca Ceoil Blue works natively on macOS thanks to the Godot engine. Official releases are also fully notarized with Apple and should work without a hitch on all modern mac-devices. These issues should be resolved now.

#### "Bosca online doesn't work"

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/61
- [x] https://github.com/TerryCavanagh/boscaceoil/issues/78
- [x] https://github.com/TerryCavanagh/boscaceoil/issues/92

Status: ✅ **Resolved**, **3.1**.

Bosca Ceoil Blue offers a web version starting with release 3.1. It works correctly in Chrome and other Chromium-based browsers (like Edge, Opera, and many others), and in Firefox. Safari has issues which affect the engine that Bosca Ceoil Blue uses, so it cannot be supported at this time.

The experience of the web version is absolutely identical, except the Esc to quit shortcut is removed. The web version also features a landing page before the app starts, letting you know if your browser is likely compatible. This version should work across all devices that have compatible browsers, including Chromebooks and Android devices (although do note that the experience is not adapted to touch screens).

See also: https://github.com/YuriSizov/boscaceoil-blue/issues/8.

## Improvements

- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/105
  - Status: 🚫 **Not implemented**.
  - I'm not against supporting alternative distributions in principle, for any platform, but I have no experience setting up any of them, nor a good idea which would be practical and which would be superfluous. But please, feel free to open issues for each platform and distribution system that you think we must support, with some details about how it would work.

- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/106
  - Status: 🚫 **Not implemented**.
  - There are currently no plans for integrating Bosca in other musical software. It can be fun, but it's not something that I'm familiar with to be the best judge of the practicality of it. Still, if you know how to do it, please make an issue or a PR with the necessary changes.

### Usability

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/39
  - Status: ✅ **Resolved**, **3.0**.
  - Bosca Ceoil Blue has full support for undo/redo a.k.a. action history. It remembers the last 40 steps, which is currently not configurable.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/41
  - Status: ✅ **Resolved**, **3.0-3.1**.
  - Overall, the new version of Bosca supports various keyboard shortcuts, including saving and saving as a copy. All of them are listed in the help section too!
  - As of version 3.1, there are now shortcuts for creating a new file (<kbd>Ctrl + N</kbd>) and for opening an existing file (<kbd>Ctrl + O</kbd>).

- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/43
  - Status: 🚫 **Not implemented**.
  - Seems like a good idea, akin to the recent change to support the DoReMi format.

- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/45
  - Status: 🚫 **Not implemented**.
  - Not currently implemented, but is a good idea. Should work to place notes while playing (only for the current pattern), and we need to somehow lock the octave (by clicking on the right sidebar, where octaves are labeled?). Also drumkits are problematic, but a solution can be as simple as using the same octave locking mechanism for a portion of drumkit items.
  - Tracked here: https://github.com/YuriSizov/boscaceoil-blue/issues/57.

- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/46
  - Status: 🚫 **Not implemented**.
  - Good idea and something that people often request. Godot has native support for MIDI inputs, but I'd like to have an actual device that I can test this with. Same considerations as above can apply, since not all MIDI devices would be able to cover the entire range of notes available in Bosca.
  - Tracked here: https://github.com/YuriSizov/boscaceoil-blue/issues/58.

- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/49
  - Status: 🚫 **Not implemented**.
  - This is a good idea and was proposed by some users of Bosca Ceoil Blue as well.
  - Tracked here: https://github.com/YuriSizov/boscaceoil-blue/issues/47.

- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/54
  - Status: 🚫 **Not implemented**.
  - This is a good idea, surprised that Terry himself added these limits and then made a proposal to remove them as unreasonable 🙃 There are some considerations, though, as various external formats that we support for export have very strict limits. For some we hit the limits already and not every Bosca song can be exported to them. Raising/removing these limits would further this problem.
  - Not much we can do about it, though. Just need to be careful with exporters, since they may be assuming stuff that is currently true for Bosca song limits (e.g. the 16 instrument limit).

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/58
  - Status: ✅ **Resolved**, **3.0**.
  - Duplicate of https://github.com/TerryCavanagh/boscaceoil/issues/39.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/59
  - Status: ✅ **Resolved-ish**, **3.0**.
  - In Bosca Ceoil Blue you can use the shortcuts to quickly save the file. Pressing <kbd>Ctrl + S</kbd> will save existing files without any extra prompts, and will prompt for a file name if it's a new file. Pressing <kbd>Ctrl + Alt + S</kbd> will always prompt for a file name with a "Save as" dialog.
  - The "Save" button always triggers the dialog, however there is a [proposal to split it into two actions](https://github.com/YuriSizov/boscaceoil-blue/issues/16) as well. I'm still considering if this is necessary given the availability of shortcuts.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/64
  - Status: ✅ **Resolved**, **3.1**.
  - As far as I understand this is asking for the ability to select and copy notes across patterns. This is something that has been requested a few times, and is now implemented in 3.1.
  - Tracked here: https://github.com/YuriSizov/boscaceoil-blue/issues/59.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/67
  - Status: ✅ **Resolved**.
  - Marking it as resolved because these suggestions are either covered by other tickets, or have been resolved already in Bosca Ceoil Blue.

- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/70
  - Status: 🚫 **Not implemented**.
  - I agree with the idea that the current format is subpar in many aspects. I will have to rework it in the future major release (4.0), but my plan was to make it binary instead, so it's nice and compact, and can only be written one way. But a binary file would not be version control friendly, which is actually a very strong argument against it. It's something that I'd have to consider when I start working on 4.0.
  - See also: https://github.com/YuriSizov/boscaceoil-blue/issues/1

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/77
  - Status: ✅ **Resolved**, **3.0**.
  - Bosca Ceoil Blue remembers the last folder that you've interacted with. It might be worth to store paths more granularly (separate for load, save, import, export?). But it's not worth overcomplicating things unless someone asks for it.

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/100
  - Status: ✅ **Resolved**, **2.x**.
  - If I understand correctly, the request is for the ability to duplicate patterns. Which you can already do as you compose the arrangement. I'm not sure being able to do it via the dock (the only other place where you could reasonably do it) significantly improves the process. So considering this resolved.
  - Terry's note is curious, but I don't think it's related to the question.

- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/101
  - Status: 🚫 **Not implemented**.
  - Duplicate of https://github.com/TerryCavanagh/boscaceoil/issues/46.
  - Tracked here: https://github.com/YuriSizov/boscaceoil-blue/issues/58.

### Music theory

- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/42
- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/44
- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/48
- [ ] https://github.com/TerryCavanagh/boscaceoil/issues/103

Status: 🚫 **Unfixed**.

These problems generally involve changing the file format that Bosca uses. As such, they can only be done in a major release where we can break compatibility. I plan to address these in Bosca Ceoil Blue 4.0 some time next year.

## Support questions and other inquiries

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/63
  - Status: ✅ **Resolved**.
  - Yes, new updates we have for you!

- [x] https://github.com/TerryCavanagh/boscaceoil/issues/86
  - Status: ✅ **Resolved**.
  - A GitHub-related suggestion. This repository, as it so happens, does use the Discussions board alongside the Issues.
